### ISSUE TITLE
Failed NPM authentication with v5.1.15

### ISSUE THREAD

**Issue by mohatt** [semantic-release/npm#190]
Once I upgraded @semantic-release/npm from v5.1.14 to v5.1.15 the automatic release process started to fail with NPM authentication error
```sh
$ semantic-release
[00:26:51] [semantic-release] › ℹ  Running semantic-release version 15.13.24
[00:26:51] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[00:26:51] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[00:26:51] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[00:26:51] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[00:26:51] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[00:26:51] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[00:26:51] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[00:26:51] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[00:26:51] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[00:26:51] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[00:26:51] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[00:26:51] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[00:26:51] [semantic-release] › ✔  Run automated release from branch master
[00:26:52] [semantic-release] › ✔  Allowed to push to the Git repository
[00:26:52] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[00:26:52] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[00:26:52] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[00:26:52] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[00:26:52] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /home/travis/build/mohatt/gatsby-plugin-advanced-pages/.npmrc
[00:26:53] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[00:26:53] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[00:26:53] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[00:26:53] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[00:26:53] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[00:26:55] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #14.
[00:26:56] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #14: https://github.com/mohatt/gatsby-plugin-advanced-pages/issues/14#issuecomment-524126786.
[00:26:56] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[00:26:56] [semantic-release] › ✖  EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry https://registry.npmjs.org/.
If you are using Two-Factor Authentication, make configure the auth-only level (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) is supported. semantic-release cannot publish with the default auth-and-writes level.
Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.
{ AggregateError: 
    SemanticReleaseError: Invalid npm token.
        at module.exports (/home/travis/build/mohatt/gatsby-plugin-advanced-pages/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/home/travis/build/mohatt/gatsby-plugin-advanced-pages/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/verify-auth.js:21:33)
        at <anonymous>
    at /home/travis/build/mohatt/gatsby-plugin-advanced-pages/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) name: 'AggregateError' }error Command failed with exit code 1.
```

Downgraded to v5.1.14 and everything is back to normal.

**Comment by ffflorian** [comment]
It must have to do something with the dependencies, since it also fails when adding v5.1.14 to a new project.

**Comment by mohatt** [comment]
yeah, I can confirm its an issue with dependencies since there were [no code changes](https://github.com/semantic-release/npm/compare/v5.1.14...v5.1.15) between v5.1.14 and v5.1.15, but I have no idea which dependency is causing the issue

**Comment by mohatt** [comment]
Managed to fix the issue by removing `yarn.lock` file and `node_modules` directory and running a fresh `yarn install`.
I also removed `@semantic-release/npm` from my `package.json` file and let `semantic-release` package handle it.

**Comment by good-idea** [comment]
I had this same issue upgrading from 5.1.13 to 5.1.15. Removing `yarn.lock` + `node_modules` and reinstalling fixed the issue. If it's of any help, or if this continues to be an issue, here's the diff of the new `yarn.lock` that got it working:

https://patch-diff.githubusercontent.com/raw/good-idea/use-shopify/pull/30.diff

Might be related to this bit:

```
-"@semantic-release/npm@^5.0.5":
-  version "5.1.7"
-  resolved "https://registry.yarnpkg.com/@semantic-release/npm/-/npm-5.1.7.tgz#ed3bac977d46294bfd11df7621bb5a9b6d5523be"
-  integrity sha512-4THiFGp9APX1a+EJJsOYurJCR8TrRUgNCU9u46AkZekWfvtyzacfIBKCrmEljpYG8qDDnHLZwHSqyW4ID4iteA==
-  dependencies:
-    "@semantic-release/error" "^2.2.0"
-    aggregate-error "^3.0.0"
-    execa "^1.0.0"
-    fs-extra "^7.0.0"
-    lodash "^4.17.4"
-    nerf-dart "^1.0.0"
-    normalize-url "^4.0.0"
-    npm "^6.8.0"
-    rc "^1.2.8"
-    read-pkg "^5.0.0"
-    registry-auth-token "^3.3.1"
-
-"@semantic-release/npm@^5.1.15":
+"@semantic-release/npm@^5.0.5", "@semantic-release/npm@^5.1.15":
   version "5.1.15"
   resolved "https://registry.yarnpkg.com/@semantic-release/npm/-/npm-5.1.15.tgz#dbf5e37bc4ce4be0a48a82c27ca4ad1e584f12ee"
   integrity sha512-MUUKOOtqsX/aJZJIjiAdw7SkCH+D3De060l1HhTlqrwTB7PzMtXcUMen6Prd1Hv8+gknUFkSWhVmi8tIaGDVnA==
@@ -738,22 +616,7 @@
     read-pkg "^5.0.0"
     registry-auth-token "^4.0.0"
```
