### ISSUE TITLE
TypeError: Found non-callable @@iterator on verify conditions

### ISSUE THREAD

**Issue by semoal** [semantic-release/npm#207]
As the title says, our pipeline on Gitlab stopped working. It's using node:10-alpine.

```sh
[10:37:04 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Found non-callable @@iterator
    at verifyConditions (/builds/secret/secretlibraries/react-ui-kit/node_modules/semantic-release/node_modules/@semantic-release/npm/index.js:39:12) pluginName: '@semantic-release/npm' }
{ AggregateError: 
    TypeError: Found non-callable @@iterator
        at verifyConditions (/builds/secret/secretlibraries/react-ui-kit/node_modules/semantic-release/node_modules/@semantic-release/npm/index.js:39:12)
    at /builds/secret/secretlibraries/react-ui-kit/node_modules/semantic-release/lib/plugins/pipeline.js:54:11 name: 'AggregateError' }npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @secretbank/react-ui-kit@2.12.0-canary.38 semantic-release: `npx semantic-release --debug`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @secretbank/react-ui-kit@2.12.0-canary.38 semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

Versions of semantic-release/npm tried: ["5.2.0-beta.6", "^6.0.0-beta.1", "5.3.0", "5.2.0"]

**Comment by semoal** [comment]
Probably is not related directly to npm package, since i put all the semantic release packages on a fixed version, and the issue got fixed.

I paste the package.json..
```json
    "@semantic-release/changelog": "3.0.4",
    "@semantic-release/commit-analyzer": "7.0.0-beta.2",
    "@semantic-release/exec": "3.3.6",
    "@semantic-release/git": "7.1.0-beta.3",
    "@semantic-release/npm": "5.2.0",
    "semantic-release": "16.0.0-beta.22",
```

**Comment by pvdlg** [comment]
So is your problem solved? If it is please close the issue.

**Comment by semoal** [comment]
The problem is solved but i guess is some bug on the other libraries. I close anyways.

**Comment by oytuntez** [comment]
We are having the same issue in multiple environments. @semoal, your versions didn't work for us.


```
[9:30:40 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.26
[9:30:40 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[9:30:40 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[9:30:40 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:30:40 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:30:40 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[9:30:40 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[9:30:40 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[9:30:40 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[9:30:42 PM] [semantic-release] › ✔  Run automated release from branch master
[9:30:43 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:30:43 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[9:30:43 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[9:30:43 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[9:30:43 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[9:30:43 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[9:30:43 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Found non-callable @@iterator
    at verifyConditions (/Users/oytun/motaword/redux/node_modules/semantic-release/node_modules/@semantic-release/npm/index.js:39:12) pluginName: '@semantic-release/npm' }
{ AggregateError: 
    TypeError: Found non-callable @@iterator
        at verifyConditions (/Users/oytun/motaword/redux/node_modules/semantic-release/node_modules/@semantic-release/npm/index.js:39:12)
    at /Users/oytun/motaword/redux/node_modules/semantic-release/lib/plugins/pipeline.js:54:11 name: 'AggregateError' }npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @motaword/redux@2.8.0 release: `npm audit fix && npm run build && semantic-release --no-ci --allow-same-version`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @motaword/redux@2.8.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by Kampfmoehre** [comment]
I had the same error when I upgrade semantic release versions.
The old config where it was working was:
```json
"@semantic-release/changelog": "^3.0.4",
"@semantic-release/git": "^7.0.16",
"@semantic-release/gitlab": "^4.0.0",
"@semantic-release/npm": "^5.1.15",
"semantic-release": "^15.13.24"
```
Then I upgraded to:
```json
"@semantic-release/changelog": "^3.0.5",
"@semantic-release/git": "^7.0.17",
"@semantic-release/gitlab": "^4.0.3",
"@semantic-release/npm": "^5.3.1",
"semantic-release": "^15.13.28"
```
and I got the error. I just downgraded `@semantic-release/npm` back to 5.1.15 and it's working again.

**Comment by oytuntez** [comment]
That worked, thank you @Kampfmoehre.
