### ISSUE TITLE
Publish with pkgRoot and .npmrc not working

### ISSUE THREAD

**Issue by johnmcase** [semantic-release/npm#359]
I have been testing out semantic-release in a sample repository of mine and have been publishing packages to a private NPM repository.  To configure publishing to the private repo I have a `.npmrc` file in the root of my project that sets the `registry` property to my private repo.  Then I have a `~/.npmrc` file (in my user dir) that contains all the auth token stuff needed to authenticate.

This setup had been working with semantic-release and this npm plugin perfectly well until I switched things up and setup a `pkgRoot` property to publish from a `dist/` directory

After making that change, I'm getting the following error output.  The info message says that is trying to `Verify authentication for registry https://registry.npmjs.org/`.  I checked and previously that line had been outputting the proper URL for my private NPM repository.

```
[12:07:03 PM] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/npm"
[12:07:03 PM] [semantic-release] [@semantic-release/npm] » i  Verify authentication for registry https://registry.npmjs.org/
[12:07:03 PM] [semantic-release] [@semantic-release/npm] » i  Reading npm config from C:\Users\jcase\.npmrc, C:\Users\jcase\repos\beautimus\gitflow-pipelines\.npmrc
[12:07:03 PM] [semantic-release] » ×  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[12:07:03 PM] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/git"
[12:07:03 PM] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/git"
[12:07:03 PM] [semantic-release] » ×  ENONPMTOKEN No npm token specified.
An npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the NPM_TOKEN environment variable on your CI environment.

Please make sure to create an npm token (https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the NPM_TOKEN environment variable on your CI environment. The token must allow to publish to the registry https://registry.npmjs.org/.

AggregateError:
    SemanticReleaseError: No npm token specified.
        at module.exports (C:/Users/jcase/repos/beautimus/gitflow-pipelines/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (C:/Users/jcase/repos/beautimus/gitflow-pipelines/node_modules/@semantic-release/npm/lib/set-npmrc-auth.js:45:31)
        at async module.exports (C:/Users/jcase/repos/beautimus/gitflow-pipelines/node_modules/@semantic-release/npm/lib/verify-auth.js:17:3)
        at async verifyConditions (C:/Users/jcase/repos/beautimus/gitflow-pipelines/node_modules/@semantic-release/npm/index.js:36:7)
        at async validator (C:/Users/jcase/repos/beautimus/gitflow-pipelines/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
        at async C:/Users/jcase/repos/beautimus/gitflow-pipelines/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
        at async Promise.all (index 0)
        at async next (C:/Users/jcase/repos/beautimus/gitflow-pipelines/node_modules/p-reduce/index.js:16:18)
    at C:\Users\jcase\repos\beautimus\gitflow-pipelines\node_modules\semantic-release\lib\plugins\pipeline.js:54:11
    at async Object.pluginsConf.<computed> [as verifyConditions] (C:\Users\jcase\repos\beautimus\gitflow-pipelines\node_modules\semantic-release\lib\plugins\index.js:80:11)
    at async run (C:\Users\jcase\repos\beautimus\gitflow-pipelines\node_modules\semantic-release\index.js:95:3)
    at async module.exports (C:\Users\jcase\repos\beautimus\gitflow-pipelines\node_modules\semantic-release\index.js:260:22)
    at async module.exports (C:\Users\jcase\repos\beautimus\gitflow-pipelines\node_modules\semantic-release\cli.js:55:5)
```

It seems that as soon as the `pkgRoot` property is set it is no longer finding the `.npmrc` file at the root of the project repository.

I should note that since I'm just testing out semantic-release I've been doing everything locally with the `--no-ci` flag set, but I can't imagine that makes a difference here.

This appears to be very similar to #215 but I don't think that issue was dealing with a `.npmrc` at the root of the project.

**Comment by johnmcase** [comment]
Nevermind.  I figured it out.

The problem was that the package.json that I had in the dist folder did not have the same npm scope applied to it as the outer package.json, therefore it was not configured to go to the private repo.  Once I applied the proper scope it all worked.
