### ISSUE TITLE
`npm publish` failing: `The "path" argument must be of type string. Received undefined`

### ISSUE THREAD

**Issue by RebeccaStevens** [semantic-release/npm#508]
Here's the error message I'm getting:

```sh
[semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/npm"
[semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: npm publish /home/runner/work/eslint-plugin-functional/eslint-plugin-functional --userconfig /tmp/7c6b96ef55c0a1b079c4f7fc30132c20/.npmrc --tag latest --registry https://registry.npmjs.org/
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/[202](https://github.com/eslint-functional/eslint-plugin-functional/runs/8109456108?check_suite_focus=true#step:8:203)2-08-31T08_40_43_011Z-debug-0.log
    at makeError (/home/runner/work/eslint-plugin-functional/eslint-plugin-functional/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/eslint-plugin-functional/eslint-plugin-functional/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/runner/work/eslint-plugin-functional/eslint-plugin-functional/node_modules/@semantic-release/npm/lib/publish.js:30:5)
    at async validator (/home/runner/work/eslint-plugin-functional/eslint-plugin-functional/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/eslint-plugin-functional/eslint-plugin-functional/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/runner/work/eslint-plugin-functional/eslint-plugin-functional/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: npm publish /home/runner/work/eslint-plugin-functional/eslint-plugin-functional --userconfig /tmp/7c6b96ef55c0a1b079c4f7fc30132c20/.npmrc --tag latest --registry https://registry.npmjs.org/',
  command: 'npm publish /home/runner/work/eslint-plugin-functional/eslint-plugin-functional --userconfig /tmp/7c6b96ef55c0a1b079c4f7fc30132c20/.npmrc --tag latest --registry https://registry.npmjs.org/',
  escapedCommand: 'npm publish "/home/runner/work/eslint-plugin-functional/eslint-plugin-functional" --userconfig "/tmp/7c6b96ef55c0a1b079c4f7fc30132c20/.npmrc" --tag latest --registry "https://registry.npmjs.org/"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm ERR! code ERR_INVALID_ARG_TYPE\n' +
    'npm ERR! The "path" argument must be of type string. Received undefined\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /home/runner/.npm/_logs/2022-08-31T08_40_43_011Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/npm'
}
```

[Link to full log](https://github.com/eslint-functional/eslint-plugin-functional/runs/8109456108?check_suite_focus=true)

I'm not really sure what's going wrong here. Any ideas?

**Comment by RebeccaStevens** [comment]
Seems like this was caused by this snippet in the workflow config:

```sh
      - run: npm install -g yarn
      - run: corepack enable
```

Removing it fixed the issue.
