### ISSUE TITLE
EINVALIDNPMTOKEN in v21.x

### ISSUE THREAD

**Issue by kpruden** [semantic-release/npm#612]
The latest version of semantic-release (21.0.2) seems to have an issue publishing npm packages in a CI environment (if it matters, I use CircleCI).

I have confirmed that my NPM_TOKEN environment variable is set correctly. The last version that works is 20.1.3

Here is the output:
```
yarn semantic-release
yarn run v1.22.19
$ /home/circleci/go/src/github.com/******/datasets/node_modules/.bin/semantic-release
[6:02:47 PM] [semantic-release] › ℹ  Running semantic-release version 21.0.2
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[6:02:47 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[6:02:50 PM] [semantic-release] › ✔  Run automated release from branch master on repository git@github.com:******/datasets.git
[6:02:50 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:02:50 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[6:02:50 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[6:02:50 PM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /home/circleci/.npmrc
/home/circleci/go/src/github.com/******/datasets/node_modules/npm/lib/cli.js:35
    throw err
    ^

TypeError: Class extends value #<Object> is not a constructor or null
    at Object.<anonymous> (/home/circleci/go/src/github.com/******/datasets/node_modules/npm/node_modules/fs-minipass/lib/index.js:136:4)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/circleci/go/src/github.com/******/datasets/node_modules/npm/node_modules/cacache/lib/content/read.js:4:13)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.16.0
[6:02:50 PM] [semantic-release] › ✘  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[6:02:50 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[6:02:50 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[6:02:51 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[6:02:51 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[6:02:52 PM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #186.
[6:02:53 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #186: https://github.com/******/datasets/issues/186#issuecomment-1530021498.
[6:02:53 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[6:02:53 PM] [semantic-release] › ✘  EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry https://registry.npmjs.org/.

If you are using Two Factor Authentication for your account, set its level to "Authorization only" (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) in your account settings. semantic-release cannot publish with the default "
Authorization and writes" level.

Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.
```

**Comment by kpruden** [comment]
Update: I've been able to trace the issue down to [the call to `npm whoami`](https://github.com/semantic-release/npm/blob/410b73dd3f9c3b2ec2aad448dedff86ad5b88660/lib/verify-auth.js#L21)

In the same environment (I've ssh'd into a CircleCI build node), calling `npm whoami` directly seems to work, using the same values for `--userconfig` and `--registry` as are used by `semantic-release`. My best guess is there's something wrong with the `env` object provided in the call to `execa`, but it's infeasible to try to recreate it by hand to confirm.

This does _not_ appear to be version-dependent. I've seen it both work and fail on 19.0.5 and 20.1.3. This problem initially started when I upgraded to version 21.x, which also necessitated an upgrade to node 18.x. However, reverting everything back to the previous versions (19.0.5 on node 16.x, which had been working without incident for some time) does not fix it. This points pretty convincingly to an environment issue, but I'm at a bit of a loss as to where to look next. My `.npmrc` find and `NPM_TOKEN` environment variables appear to be correct.

**Comment by jwarykowski** [comment]
Hey @kpruden, thanks for the detailed feedback above. If possible can you let me know the versions of `node`, `npm`, `semantic-release` and `@semantic-release/npm`? I've spent half a day looking at this to no avail 😢 Any feedback would be greatly appreciated. Note I'm seeing the issue in AWS code build.
